export const iProductos = [
    {id:0, name:'Taladro', price:5000,stock:5,imagen:"../imagenes/taladro1.webp",category:'Herramientas Manuales',descripcion:'• Taladro / Atornillador inalámbrico de 13mm. Equipo de alta potencia, con un torque máximo de 56 Nm y hasta 1800 RPM. Versión en kit con 2 baterías incluídas. Incluye luz LED para iluminar el área de trabajo.'},
    {id:1, name:'Compresor Stanley', price:15000,stock:10,imagen:"../imagenes/compresor1.webp",category:'Herramientas Electricas',descripcion:'Su potencia de 2hp lo convierte en la herramienta necesaria para labores domésticas que requieren un nivel bajo de presión. Además, la capacidad del tanque de 25l permite usos puntuales y por un corto período de tiempo, lo que te permitirá recargarlo rápidamente para volver a utilizarlo cuando quieras.'},
    {id:2, name:'Hidrolavadora', price:20000,stock:12,imagen:"../imagenes/hidro1.webp",category:'Herramientas Electricas',descripcion:'Con tu hidrolavadora podés dejar reluciente cualquier material o superficie. Su rocío de agua de alta presión es entre diez y cincuenta veces más potente que las mangueras de jardín, lo que hace más eficaz y fácil el proceso de limpieza.Gracias a su presión máxima de 130 bar, esta hidrolavadora genera un impacto potente sobre distintas superficies. ¡Ya no habrá suciedad que se resista a tanta presión!'},
    {id:3, name:'Soldadora', price:50000,stock:15,imagen:"../imagenes/soldar1.webp",category:'Soldadura',descripcion:'Maquina de soldar'},
    {id:4, name:'Taladro Milwaukee', price:20000,stock:12,imagen:"../imagenes/taladromilwa.webp",category:'Herramientas Manuales',descripcion:'Con tu hidrolavadora podés dejar reluciente cualquier material o superficie. Su rocío de agua de alta presión es entre diez y cincuenta veces más potente que las mangueras de jardín, lo que hace más eficaz y fácil el proceso de limpieza.Gracias a su presión máxima de 130 bar, esta hidrolavadora genera un impacto potente sobre distintas superficies. ¡Ya no habrá suciedad que se resista a tanta presión!'},
    {id:5, name:'Kit Herramientas', price:20000,stock:12,imagen:"../imagenes/kitherramientas.webp",category:'Herramientas Manuales',descripcion:'Caja de Herramientas de 142 Pcs INDUSTRIAL TOTAL THKTHP21426- 142 Piezas- 3 llave de tubo con crique, encastre 1/4, 3/8 y 1/2- 1 llave de tubo larga, encastre 1/2- 9 tubos hexagonales (de 4 a 10 mm), encastre 1/- 5 tubos torx hembra (de 4 a 8mm), encastre 1/- 15 tubos estriados (de 6 a 22 mm), encastre 3/8- 5 tubos torx hembra (de 10 a 20 mm), encastre 1/2- 19 tubos hexagonales (de 8 a 32mm), encastre 1/2- 2 llaves saca bujía de 16mm y 21mm, encastre 1/2- 3 uniones cardánicas de 1/4”, 3/8 y 1/2”- 1 acople encastre 1/4 a hexagonal- 2 T deslinzante y adaptadores de 3/8 x 1/4 y 3/8 x 1/2- 7 barras de extensión, encastre 1/4, 3/8 y 1/2- 1 barra de extensión flexible, encastre 1/4- 1 barra L 1/2 x 1- 1 mango destornillador 1/4- 3 puntas destornillador plan- 8 puntas destornillador philips- 7 puntas destornillador torx- 8 puntas destornillador hexagonal- 10 llaves alen (2,5 a 14mm)- 1 martill- 1 alicate de presión- 1 pinza con alicate- 3 destornilladores plan- 3 destornilladores philip- 17 llaves combinadas (de 6 a 24 mm)- 5 llaves doble hexagonal abierta (de 8 a 19mm)'},
    {id:6, name:'Juego de tubos', price:20000,stock:12,imagen:"../imagenes/juegodetubos.webp",category:'Herramientas Manuales',descripcion:'- 20 piezas 1/4 set: 4, 5, 6, 7, 8, 9, 10, 11, 12,13 mm; 3/16, 7/32, 1/4, 9/32, 5/16, 11/32, 3/8,7/16, 1/2, 9/16.- 16 piezas 3/8 set: 9, 10, 12, 13, 14, 15, 17.19 mm; 5/16, 3/8, 7/16, 1/2, 9/16, 5/8, 11/16, 3/4.- 10 piezas 3/8 set: 12, 13, 14, 15, 17 mm; 7/16,1/2, 9/16, 11/16, 3/4.- 18 piezas hexagonales, 1/16, 5/64, 3/32, 1/8, 5/32, 3/16, 1/4,5/16, 3/8.- 12 piezas, llave combinada: 8, 10, 12, 13, 14,15 mm; 5/16, 3/8, 7/16, 1/2, 9/16, 5/8.- 3 piezas ratchet: 1/4, 3/8, 1/2.- 4 piezas, barra extensible: 1/4 dr x 50mm;3/8 dr x 75mm; 3/8 dr x 150mm; 1/2 dr x 75mm.- 4 piezas, destornilladores: 5.5 x 100mm (slot),6.5 x 100mm (slot), #1 x 75mm (Ph),#2 x 100mm (Ph).- 1 pieza, boquilla magnética:- 1 pz 8, alicate punta larga- 1 pz 6 Alicate Corte Oblicuo'},
    {id:7, name:'Hidrolavadora Ducati', price:20000,stock:12,imagen:"../imagenes/hidro2.webp",category:'Herramientas Electricas',descripcion:'Hidrolavadora Ducati DPW 2100, tiene potencia de 2100W, presión de trabajo de 130 bar, caudal de 420 litros por hora, funciona por inducción.'},
    {id:8, name:'Hidrolavadora', price:20000,stock:12,imagen:"../imagenes/hidro1.webp",category:'Herramientas Electricas',descripcion:'Con tu hidrolavadora podés dejar reluciente cualquier material o superficie. Su rocío de agua de alta presión es entre diez y cincuenta veces más potente que las mangueras de jardín, lo que hace más eficaz y fácil el proceso de limpieza.Gracias a su presión máxima de 130 bar, esta hidrolavadora genera un impacto potente sobre distintas superficies. ¡Ya no habrá suciedad que se resista a tanta presión!'},
    {id:9,name:'Soldador', price:20000,stock:12,imagen:"../imagenes/soldadorain.webp",category:'Soldadura',descripcion:'Stanley Sirio 140 es ideal para uso doméstico y profesional. Su calidad brinda una fusión precisa, para que puedas soldar diversos materiales, aplicando calor y proporcionando mayor resistencia.Tecnología eficazAl ser de tipo MMA, cuenta con una salida de corriente alterna y es apta para el uso de electrodos especiales y comunes.La principal ventaja es que puede utilizarse en cualquier posición en casi todos los materiales, lo que la convierte en la compañera ideal para soldar uniones que no se pueden colocar en la posición plana.Voltaje estable sin picosGracias a su tecnología inverter disfrutarás de mayor facilidad y calidad a la hora de soldar. Se caracteriza por un menor consumo de energía y por ofrecer un arco mucho más estable y seguro, sin picos de voltaje.Además, podrás controlar la potencia de salida de forma más precisa gracias a su regulación electrónica.'}
]  



